auto:        true
destination: ../bin-debug
plugins:     ./_plugins
permalink: none
exclude: [less]

ideal_tag_line: Moving ideas to the next level
ideal_features_list: 
  - Social engagement
  - Idea creation
  - Analytics
  - Facebook & twitter integration
  - Slick design
  - SEO freindly
  - Pluggable - Drupal Appstore <span class="label notice">Soon</span>
  - Ajax comments
  - Administration reports
  - Exportable widgets
  - Fully customized
  - Turnkey cloud hosting plan <span class="label notice">Soon</span>
  - Multilingual
  - Open source - Drupal 7 based
  
ideal_in_the_box:
  - Home Page
  - Idea creation
  - Idea presentation + comments
  - Category / Tag page
  - Popular ideas
  - Recent ideas
  - Profile page
  - Search for ideas
  - Search for members
  - Project page
  - Trends & analytics reports
  - Q&A