auto:        true
destination: ../bin-debug
plugins:     ./_plugins
permalink: none
exclude: [less]

ideal_tag_line: Moving ideas to the next level
ideal_in_the_box:
  - Home Page
  - Registartion
  - Log in
  - Idea creation
  - Idea presentation + comments
  - Category / Tag page
  - Popular ideas
  - Recent ideas
  - In-Process ideas
  - Launched ideas
  - Profile page (My page + someone else\'s page)
  - Search for ideas
  - Search for members
  - Project page
  - Q&A